/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.estruturados;

public class App {
    public static void main(String[] args) {
        Pilha pilha = new Pilha(10);
        pilha.insere(10);
        pilha.insere(30);
        pilha.insere(50);
        pilha.insere(100);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
        pilha.insere(50);
       
        
        pilha.imprime();
    }
}
