/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.estruturados;

public class App {
    public static void main(String[] args) {
        Fila fila = new Fila(10);
        fila.insere(10);
        fila.insere(20);
        fila.insere(30);
        fila.remove();
        fila.remove();
        fila.remove();
        fila.remove();
        
        
        fila.imprime();
    }
}
